### ISSUE TITLE
Still getting the linking error in #16 in the release version (1.3.1)

### ISSUE THREAD

**Issue by c200chromebook** [pygraphviz/pygraphviz#74]
Hi there - I'm still getting the linking error in #16 trying to build using WinPython w/ python 3.4.3 and Visual Studio 10. Suggestions?

Most relevant bit:

```
graphviz_wrap.obj : error LNK2019: unresolved external symbol _PyIOBase_Type ref
erenced in function __wrap_agread
```

```
include_dirs=C:\Program Files (x86)\Graphviz2.38\include
library_dirs=C:\Program Files (x86)\Graphviz2.38\lib\debug\lib
running build
running build_py
running egg_info
writing dependency_links to pygraphviz.egg-info\dependency_links.txt
writing pygraphviz.egg-info\PKG-INFO
writing top-level names to pygraphviz.egg-info\top_level.txt
reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc\build'
writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
running build_ext
building 'pygraphviz._graphviz' extension
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox
 /MD /W3 /GS- /DNDEBUG "-IC:\Program Files (x86)\Graphviz2.38\include" -IC:\winp
y\python-3.4.3\include -IC:\winpy\python-3.4.3\include /Tcpygraphviz/graphviz_wr
ap.c /Fobuild\temp.win32-3.4\Release\pygraphviz/graphviz_wrap.obj
graphviz_wrap.c
pygraphviz/graphviz_wrap.c(3321) : warning C4047: 'return' : 'int' differs in le
vels of indirection from 'Agsym_t *'
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo
 /INCREMENTAL:NO "/LIBPATH:C:\Program Files (x86)\Graphviz2.38\lib\debug\lib" /L
IBPATH:C:\winpy\python-3.4.3\libs /LIBPATH:C:\winpy\python-3.4.3\PCbuild cgraph.
lib cdt.lib /EXPORT:PyInit__graphviz build\temp.win32-3.4\Release\pygraphviz/gra
phviz_wrap.obj /OUT:build\lib.win32-3.4\pygraphviz\_graphviz.pyd /IMPLIB:build\t
emp.win32-3.4\Release\pygraphviz\_graphviz.lib /MANIFESTFILE:build\temp.win32-3.
4\Release\pygraphviz\_graphviz.pyd.manifest
   Creating library build\temp.win32-3.4\Release\pygraphviz\_graphviz.lib and ob
ject build\temp.win32-3.4\Release\pygraphviz\_graphviz.exp
graphviz_wrap.obj : error LNK2019: unresolved external symbol _PyIOBase_Type ref
erenced in function __wrap_agread
build\lib.win32-3.4\pygraphviz\_graphviz.pyd : fatal error LNK1120: 1 unresolved
 externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\
link.exe' failed with exit status 1120
```

**Comment by c200chromebook** [comment]
For those who prefer their errors gcc-flavored:
```
include_dirs=C:\Program Files (x86)\Graphviz2.38\include
library_dirs=C:\Program Files (x86)\Graphviz2.38\lib\debug\lib
running build
running build_py
running egg_info
writing top-level names to pygraphviz.egg-info\top_level.txt
writing dependency_links to pygraphviz.egg-info\dependency_links.txt
writing pygraphviz.egg-info\PKG-INFO
reading manifest file 'pygraphviz.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distributi
on
warning: no previously-included files matching '*.pyc' found anywhere in distrib
ution
warning: no previously-included files matching '.svn' found anywhere in distribu
tion
no previously-included directories found matching 'doc\build'
writing manifest file 'pygraphviz.egg-info\SOURCES.txt'
running build_ext
building 'pygraphviz._graphviz' extension
C:\winpy\python-3.4.3\..\tools\mingw32\bin\gcc.exe -mdll -O -Wall "-IC:\Program
Files (x86)\Graphviz2.38\include" -IC:\winpy\python-3.4.3\include -IC:\winpy\pyt
hon-3.4.3\include -c pygraphviz/graphviz_wrap.c -o build\temp.win32-3.4\Release\
pygraphviz\graphviz_wrap.o
pygraphviz/graphviz_wrap.c: In function 'agattr_label':
pygraphviz/graphviz_wrap.c:3321:5: warning: return makes integer from pointer wi
thout a cast
     return agattr(g, kind, name, val);
     ^
writing build\temp.win32-3.4\Release\pygraphviz\_graphviz.def
C:\winpy\python-3.4.3\..\tools\mingw32\bin\gcc.exe -shared -s build\temp.win32-3
.4\Release\pygraphviz\graphviz_wrap.o build\temp.win32-3.4\Release\pygraphviz\_g
raphviz.def "-LC:\Program Files (x86)\Graphviz2.38\lib\debug\lib" -LC:\winpy\pyt
hon-3.4.3\libs -LC:\winpy\python-3.4.3\PCbuild -lcgraph -lcdt -lpython34 -lmsvcr
100 -o build\lib.win32-3.4\pygraphviz\_graphviz.pyd
build\temp.win32-3.4\Release\pygraphviz\graphviz_wrap.o:graphviz_wrap.c:(.text+0
x1eb9): undefined reference to `PyIOBase_Type'
build\temp.win32-3.4\Release\pygraphviz\graphviz_wrap.o:graphviz_wrap.c:(.text+0
x20bc): undefined reference to `PyIOBase_Type'
C:/winpy/tools/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w6
4-mingw32/bin/ld.exe: build\temp.win32-3.4\Release\pygraphviz\graphviz_wrap.o: b
ad reloc address 0x100 in section `.data'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\winpy\\python-3.4.3\\..\\tools\\mingw32\\bin\\gcc.exe' faile
d with exit status 1
```

**Comment by DIdro** [comment]
+1 I also have this error on Win7+MSVC2010+Py3.4

**Comment by dschult** [comment]
Did anyone try the solution suggested [here](https://groups.google.com/forum/#!msg/pygraphviz-discuss/k34EinBs3pY/QhH6hDuabYEJ)?  Let us know....

**Comment by DIdro** [comment]
Yes, I use "/":

C:\Python34\Scripts>pip.exe install --global-option=build_ext --global-option="-IC:/Prog
ram Files/Graphviz2.38/include/;C:/Program Files/Microsoft SDKs/Windows/v7.1A/Include/"
--global-option="-LC:/Program Files/Graphviz2.38/lib/release/lib/;C:/Program Files/Micro
soft SDKs/Windows/v7.1A/Lib" pygraphviz

When I try to use "\" I have other errors.

**Comment by DIdro** [comment]
I've tried Python3.5 and MCVS2015(VC++14) and have the same error:(

<pre>
C:\Python35\Scripts>pip.exe install --global-option=build_ext --global-option="-IC:/Prog
ram Files/Graphviz2.38/include/;C:/Program Files/Microsoft SDKs/Windows/v7.1A/Include/"
--global-option="-LC:/Program Files/Graphviz2.38/lib/release/lib/;C:/Program Files/Micro
soft SDKs/Windows/v7.1A/Lib" pygraphviz
c:\python35\lib\site-packages\pip\commands\install.py:180: UserWarning: Disabling all us
e of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting pygraphviz
  Using cached pygraphviz-1.3.1.tar.gz
Installing collected packages: pygraphviz
  Running setup.py install for pygraphviz ... error
    Complete output from command c:\python35\python.exe -u -c "import setuptools, tokeni
ze;__file__='C:\\Users\\gmdidro\\AppData\\Local\\Temp\\pip-build-ecd29dkd\\pygraphviz\\s
etup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '
\n'), __file__, 'exec'))" build_ext "-IC:/Program Files/Graphviz2.38/include/;C:/Program
 Files/Microsoft SDKs/Windows/v7.1A/Include/" "-LC:/Program Files/Graphviz2.38/lib/relea
se/lib/;C:/Program Files/Microsoft SDKs/Windows/v7.1A/Lib" install --record C:\Users\gmd
idro\AppData\Local\Temp\pip-7p6ou31a-record\install-record.txt --single-version-external
ly-managed --compile:
    running build_ext
    building 'pygraphviz._graphviz' extension
    creating build
    creating build\temp.win32-3.5
    creating build\temp.win32-3.5\Release
    creating build\temp.win32-3.5\Release\pygraphviz
    C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /
DNDEBUG /MD "-IC:/Program Files/Graphviz2.38/include/" "-IC:/Program Files/Microsoft SDK
s/Windows/v7.1A/Include/" -Ic:\python35\include -Ic:\python35\include "-IC:\Program File
s\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files\Microsoft Visual Studio 1
4.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files\Windows Kits\10\include\10.0.10150.0\ucrt" "-
IC:\Program Files\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files\Windows Kits
\8.1\include\shared" "-IC:\Program Files\Windows Kits\8.1\include\um" "-IC:\Program File
s\Windows Kits\8.1\include\winrt" /Tcpygraphviz/graphviz_wrap.c /Fobuild\temp.win32-3.5\
Release\pygraphviz/graphviz_wrap.obj
    graphviz_wrap.c
    pygraphviz/graphviz_wrap.c(3321): warning C4047: 'return': 'int' differs in levels o
f indirection from 'Agsym_t *'
    creating C:\Users\gmdidro\AppData\Local\Temp\pip-build-ecd29dkd\pygraphviz\build\lib
.win32-3.5
    creating C:\Users\gmdidro\AppData\Local\Temp\pip-build-ecd29dkd\pygraphviz\build\lib
.win32-3.5\pygraphviz
    C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:N
O /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:/Program Files/Graphviz2.3
8/lib/release/lib/" "/LIBPATH:C:/Program Files/Microsoft SDKs/Windows/v7.1A/Lib" /LIBPAT
H:c:\python35\libs /LIBPATH:c:\python35\PCbuild\win32 "/LIBPATH:C:\Program Files\Microso
ft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files\Microsoft Visual Studio 14.0\VC
\ATLMFC\LIB" "/LIBPATH:C:\Program Files\Windows Kits\10\lib\10.0.10150.0\ucrt\x86" "/LIB
PATH:C:\Program Files\Windows Kits\NETFXSDK\4.6\lib\um\x86" "/LIBPATH:C:\Program Files\W
indows Kits\8.1\lib\winv6.3\um\x86" cgraph.lib cdt.lib /EXPORT:PyInit__graphviz build\te
mp.win32-3.5\Release\pygraphviz/graphviz_wrap.obj /OUT:build\lib.win32-3.5\pygraphviz\_g
raphviz.cp35-win32.pyd /IMPLIB:build\temp.win32-3.5\Release\pygraphviz\_graphviz.cp35-wi
n32.lib
       Creating library build\temp.win32-3.5\Release\pygraphviz\_graphviz.cp35-win32.lib
 and object build\temp.win32-3.5\Release\pygraphviz\_graphviz.cp35-win32.exp
    graphviz_wrap.obj : error LNK2001: unresolved external symbol _PyIOBase_Type
    build\lib.win32-3.5\pygraphviz\_graphviz.cp35-win32.pyd : fatal error LNK1120: 1 unr
esolved externals
    error: command 'C:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe'
failed with exit status 1120

    ----------------------------------------
Command "c:\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\
gmdidro\\AppData\\Local\\Temp\\pip-build-ecd29dkd\\pygraphviz\\setup.py';exec(compile(ge
tattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))
" build_ext "-IC:/Program Files/Graphviz2.38/include/;C:/Program Files/Microsoft SDKs/Wi
ndows/v7.1A/Include/" "-LC:/Program Files/Graphviz2.38/lib/release/lib/;C:/Program Files
/Microsoft SDKs/Windows/v7.1A/Lib" install --record C:\Users\gmdidro\AppData\Local\Temp\
pip-7p6ou31a-record\install-record.txt --single-version-externally-managed --compile" fa
iled with error code 1 in C:\Users\gmdidro\AppData\Local\Temp\pip-build-ecd29dkd\pygraph
viz
</pre>

**Comment by doolingdavid** [comment]
Has anyone gotten pygraphviz to work with python 3.5 + ? On a Windows machine.

**Comment by ahmedabt** [comment]
Facing the same issue :( .. anyone found a solution?

**Comment by ahmedabt** [comment]
all, I applied the below patch and it worked.

patch: https://github.com/Kagami/pygraphviz/commit/fe442dc16accb629c3feaf157af75f67ccabbd6e

**Comment by diogolr** [comment]
I succeeded on windows (x64) using:

- https://github.com/Kagami/pygraphviz/commit/fe442dc16accb629c3feaf157af75f67ccabbd6e, 
- [This build](https://ci.appveyor.com/project/ellson/graphviz-pl238/build/job/yv61bq4i0r0lc8w4/artifacts)
- Release: [1.3.1](https://github.com/pygraphviz/pygraphviz/archive/pygraphviz-1.3.tar.gz):
- The folowing command line:

```
python setup.py install --user --include-path=C:\\...\\graphviz\\include --library-path=C:\\...\\graphviz\\lib
```

#### Related links/issues:

https://github.com/mahkoCosmo/GraphViz_x64/issues/2#issuecomment-394180963

**Comment by RobinZerafa** [comment]
@diogolr thank you it worked for me 👍

**Comment by Aarbor1** [comment]
I'm also facing same problem ,can you please tell me the details how to apply the patch. @diogolr  @RobinZerafa

**Comment by diogolr** [comment]
Just replace the original files with the "raw" files from that commit.

**Comment by tonygrue** [comment]
I'm curious, this issue still exists in this repro right? (I just hit it.) A code change needs to be patched in from Kagami?  Since this bug was closed does that mean the project is uninterested in addressing the issue in the main repo?  Or should this issue be left open until it's addressed?

**Comment by MingweiSamuel** [comment]
Yes, the library doesn't seems to be supporting windows anymore

**Comment by keszybz** [comment]
This is now an issue on Fedora 32 with python3.9: https://bugzilla.redhat.com/show_bug.cgi?id=1792949#c3. I'll submit @Kagami's patch as PR.

**Comment by 5aurabhpathak** [comment]
@Kagami's patch not working on python 3.7 as well. Witnessing more unresolved external symbol errors after applying the patch.

**Comment by CMPdeS** [comment]
Hey guys, I realize this is a really old thread but just ran into this problem, and thought I should let you know my fix for it. It appears it happens when your graphviz and python version don't match. I had python x86 and x64 on the same machine and for some reason or other was running graphviz x64 against a x86 python. Just matched the right version to it with the command line options   
`pip install --global-option=build_ext --global-option="-IC:\Program Files (x86)\Graphviz\include" --global-option="-LC:\Program Files (x86)\Graphviz\lib" pygraphviz`   
and voila, problem solved.  

Before:  

> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Graphviz\lib" /LIBPATH:C:\Users\cezar\.virtualenvs\smart-retail-toVJUNNm\libs /LIBPATH:C:\Users\cezar\AppData\Local\Programs\Python\Python38-32\libs /LIBPATH:C:\Users\cezar\AppData\Local\Programs\Python\Python38-32 /LIBPATH:C:\Users\cezar\.virtualenvs\smart-retail-toVJUNNm\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86" cdt.lib cgraph.lib gvc.lib /EXPORT:PyInit__graphviz build\temp.win32-3.8\Release\pygraphviz/graphviz_wrap.obj /OUT:build\lib.win32-3.8\pygraphviz\_graphviz.cp38-win32.pyd /IMPLIB:build\temp.win32-3.8\Release\pygraphviz\_graphviz.cp38-win32.lib
>        Criando biblioteca build\temp.win32-3.8\Release\pygraphviz\_graphviz.cp38-win32.lib e objeto build\temp.win32-3.8\Release\pygraphviz\_graphviz.cp38-win32.exp
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agwrite
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__gvFreeContext
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agisdirected
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agopen
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agraphof
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnxtin
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__aglstnode
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agedge
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agsubedge
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agisundirected
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnxtnode
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agidnode
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__gvLayout
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__gvRender
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnxtsubg
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agisstrict
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agattrsym
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agfstin
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__gvFreeLayout
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agattr
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agstrdup_html
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__gvContext
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__Agdirected
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnameof
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agfstnode
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agget
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agdegree
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agfstedge
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agdelsubg
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agdelnode
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnxtattr
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agread
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__gvFreeRenderData
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__gvRenderFilename
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agparent
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agxset
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agclose
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agidedge
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agroot
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agfstsubg
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agdeledge
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnnodes
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__Agundirected
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agxget
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agsubnode
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnxtedge
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agsubg
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnedges
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agset
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agfstout
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__gvRenderData
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnode
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agsafeset
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agprvnode
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__Agstrictundirected
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__agnxtout
>     graphviz_wrap.obj : error LNK2001: sφmbolos externos indefinidos __imp__Agstrictdirected
>     build\lib.win32-3.8\pygraphviz\_graphviz.cp38-win32.pyd : fatal error LNK1120: 57 externo nπo resolvidos
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120
>  

After:

> $ pip install --global-option=build_ext --global-option="-IC:\Program Files (x86)\Graphviz\include" --global-option="-LC:\Program Files (x86)\Graphviz\lib" pygraphviz
> Collecting pygraphviz
>   Using cached pygraphviz-1.7.zip (118 kB)
> Skipping wheel build for pygraphviz, due to binaries being disabled for it.
> Installing collected packages: pygraphviz
>     Running setup.py install for pygraphviz: started
>     Running setup.py install for pygraphviz: finished with status 'done'
> Successfully installed pygraphviz-1.7
>
