### ISSUE TITLE
Crashes with Graphviz 14.x

### ISSUE THREAD

**Issue by szhorvat** [pygraphviz/pygraphviz#575]
When using Graphviz 14.x, a crash occurs while running the tests. Is this version of Graphviz supported? Is it documented somewhere which Graphviz versions are supported?

Note: I did not take a close look at this. We ran into this issue while investigating whether Graphviz can be safely updated from 12.x to 14.x in MacPorts.

**Comment by mgorny** [comment]
It doesn't even compile with graphviz 14.0.5:

```
x86_64-pc-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -fPIC -DSWIG_PYTHON_STRICT_BYTE_CHAR -I/tmp/build-env-j_jvx8uc/include -I/usr/include/python3.14 -c pygraphviz/graphviz_wrap.c -o build/temp.linux-x86_64-cpython-314/pygraphviz/graphviz_wrap.o
pygraphviz/graphviz_wrap.c:9:9: warning: ‘SWIG_PYTHON_STRICT_BYTE_CHAR’ redefined
    9 | #define SWIG_PYTHON_STRICT_BYTE_CHAR
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
<command-line>: note: this is the location of the previous definition
pygraphviz/graphviz_wrap.c: In function ‘_wrap_gvRenderData’:
pygraphviz/graphviz_wrap.c:5486:50: error: passing argument 5 of ‘gvRenderData’ from incompatible pointer type [-Wincompatible-pointer-types]
 5486 |   result = (int)gvRenderData(arg1,arg2,arg3,arg4,arg5);
      |                                                  ^~~~
      |                                                  |
      |                                                  unsigned int *
In file included from pygraphviz/graphviz_wrap.c:3024:
/usr/include/graphviz/gvc.h:99:49: note: expected ‘size_t *’ {aka ‘long unsigned int *’} but argument is of type ‘unsigned int *’
   99 |                          char **result, size_t *length);
      |                                         ~~~~~~~~^~~~~~
error: command '/usr/bin/x86_64-pc-linux-gnu-gcc' failed with exit code 1
```

**Comment by rossbar** [comment]
Closed by #603
