### ISSUE TITLE
Python 2.6: AttributeError: 'module' object has no attribute 'check_output'

### ISSUE THREAD

**Issue by xrobin** [pygraphviz/pygraphviz#81]
It looks like pygraphviz currently doesn't build on Python 2.6. `check_output` was introduced in 2.7. 

Here's the full stack trace:

```
xavier@congo:~/pygraphviz$ python setup.py install
running install
Trying pkg-config
Traceback (most recent call last):
  File "setup.py", line 93, in <module>
    tests_require=['nose>=0.10.1', 'doctest-ignore-unicode>=0.1.0',],
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/home/xavier/pygraphviz/setup_commands.py", line 44, in modified_run
    self.include_path, self.library_path = get_graphviz_dirs()
  File "/home/xavier/pygraphviz/setup_extra.py", line 121, in get_graphviz_dirs
    include_dirs, library_dirs = _pkg_config()
  File "/home/xavier/pygraphviz/setup_extra.py", line 44, in _pkg_config
    output = S.check_output(['pkg-config', '--libs-only-L', 'libcgraph'])
AttributeError: 'module' object has no attribute 'check_output'
```
Please consider dropping 2.6 support explicitly in `setup.py`, or apparently one can use `Popen` instead.

**Comment by hagberg** [comment]
Thanks for the report.   We need to edit setup.py to indicate we no longer support Python 2.6.
